name: go test

on: [push, pull_request]

jobs:
  test:
    env:
      AMBEE_KEY: ${{ secrets.AMBEE_KEY }}
    runs-on: ubuntu-latest
    steps:
      - name: setup go
        uses: actions/setup-go@v2
        with:
          go-version: "^1.17"
      - name: checkout
        uses: actions/checkout@v2
      - name: go test
        run: go test -v ./...
